spring.application.name=travel-web

server.port=8090

booking.service.url=http://booking-service:8081
provider.service.url=http://provider-service:8082

spring.thymeleaf.cache=false

spring.cloud.openfeign.client.config.default.connectTimeout=10000
spring.cloud.openfeign.client.config.default.readTimeout=60000