name: Java CI

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build Discovery Server
        run: mvn clean package -DskipTests
        working-directory: discovery-server

      - name: Build Provider Service
        run: mvn clean package -DskipTests
        working-directory: provider-service

      - name: Build Booking Service
        run: mvn clean package -DskipTests
        working-directory: booking-service

      - name: Build API Gateway
        run: mvn clean package -DskipTests
        working-directory: api-gateway